### ISSUE TITLE
Options are not merging into email

### ISSUE THREAD

**Issue by benpackard** [back4app/parse-server-mandrill-adapter#2]
Perhaps I am missing something but I am finding that my password reset emails are sending successfully but the various variables for `appName`, `link`, etc are not substituted. For example, my `parse-server` `index.js` includes:

```
appName: 'Songline',
  publicServerURL: process.env.SERVER_URL || 'http://localhost:1337/parse',
  emailAdapter: {
    module: 'parse-server-mandrill-adapter',
    options: {
      // API key from Mandrill account
      apiKey: 'MY_API_KEY',
      // From email address
      fromEmail: 'no-reply@songline.co',
      // Display name
      displayName: 'no-reply@songline.co',
      // Reply-to email address
      replyTo: 'no-reply@songline.co',
      // Verification email subject
      verificationSubject: 'Please verify your e-mail for *|appname|*',
      // Verification email body
      verificationBody: 'Hi *|username|*,\n\nYou are being asked to confirm the e-mail address *|email|* with *|appname|*\n\nClick here to confirm it:\n*|link|*',
      // Password reset email subject
      passwordResetSubject: 'Password Reset Request for *|appname|*',
      // Password reset email body
      passwordResetBody: 'Hi *|username|*,\n\nYou requested a password reset for *|appname|*.\n\nClick here to reset it:\n*|link|*'
    }
  }
```

But the email delivered looks like this:

```
Hi *|username|*, 

You requested a password reset for *|appname|*. 

Click here to reset it: 
*|link|*
```

Some console logging from this module's `sendVerificationEmail` confirms that `options.username`, `options.link`, etc are set correctly. But they don't make it into the email.

**Comment by benpackard** [comment]
Something in the back of my mind recalled using a different style of merge tag for Mandrill email templates - namely `{{var}}`. I swapped out the tags and the email substitutes the values correctly. E.g:

```
...
verificationBody: 'Hi {{username}},\n\nYou are being asked to confirm the e-mail address {{email}} with {{app name}}\n\nClick here to confirm it:\n{{link}}',
...
```

Any thoughts? I can submit a PR but my guess is that this is working as-is for some users.

**Comment by davimacedo** [comment]
Yes... it is working for others. Please in your Mandrill account take a look in Settings -> Sending Defaults. The last option is Merge Language. In my case I have selected MailChimp. Probably you have selected Handlebars. If yes, you could submit a PR explaining it in README. I mean, if the configuration in Mandrill is MailChimp, one should use _| ... |_ in templates, and {{ ... }}, otherwise. Best!

**Comment by benpackard** [comment]
You're right, thanks. I will submit a PR with that readme note.
