### ISSUE TITLE
customUserAttributesMergeTags is required for templates

### ISSUE THREAD

**Issue by chaimsiegel** [back4app/parse-server-mandrill-adapter#5]
perhaps this attribute should be optional

   if (typeof mandrillOptions.customUserAttributesMergeTags !== 'undefined') {
      for (var extra_attr of mandrillOptions.customUserAttributesMergeTags) {
        global_merge_vars.push({ name: extra_attr, content: options.user.get(extra_attr) || '' });
      }
    }

**Comment by alarrosa14** [comment]
Agree with this.
Referencing your pull request: #6

**Comment by davimacedo** [comment]
Hi, guys. Sorry about the delay. Just merged.
