### ISSUE TITLE
user.get('email') may be undefined

### ISSUE THREAD

**Issue by flovilmart** [back4app/parse-server-mandrill-adapter#7]
Starting that PR: https://github.com/ParsePlatform/parse-server/pull/2732 user.get('email') may be undefined for all calls but `sendMail`.

You should be prepared to use `user.get('username')` if `user.get('email')` is not set.

**Comment by davimacedo** [comment]
Thanks @flovilmart  just done on https://github.com/back4app/parse-server-mandrill-adapter/pull/9
